---
# tasks file for terraform deletion
#


- name: Update repo
  shell: "cat /etc/yum.repos.d/pbench.repo | sed \"s/ndokos\\/pbench/ndokos\\/pbench-test/g\" > /etc/yum.repos.d/pbench.repo.new"

- name: Replace repo
  shell: "mv /etc/yum.repos.d/pbench.repo.new /etc/yum.repos.d/pbench.repo"

