---
# Locate the pbench_disk
#
- name: get cloud_info
  include_vars:
    file: "{{ tf_file }}"
    name: cloud_data

- name: get pbench disk
  include_role:
    name: retrieve_pbench_disk
  vars:
    disk_info: "{{ resource_info.instances }}"
    pbench_disk_name: "{{ resource_info.name }}"
    when: "'pbench_volume' in resource_info.name"
  loop: "{{ cloud_data.resources }}"
  loop_control:
    loop_var: resource_info

