---

#
# Due to the difference in output between spot and non spot instances, we perform a grep.
# We could use the terraform state file itself, to do that would require two different checks
# here.  One for spot instances and one for non spot instances.
#
- name: wait for dns name to appear.
  command: "grep {{ look_for }} {{ working_dir }}/tf/terraform.tfstate.d/{{ config_info.system_type }}-{{ config_info.run_label }}-{{ config_info.host_or_cloud_inst }}/terraform.tfstate"
  register: dns_grep
  until: dns_grep is not failed
  retries: 2
  delay: 20

