---
# tasks file for install_tools

#
# Copy the required files.
#
- name: copy getconf.py
  copy:
    src: "{{ config_info.local_run_dir }}/bin/getconf.py"
    dest: /usr/bin
    mode: '0755'

#
# Install the epel repo key; this needs to be done due to a change in ansible.
#
- name: Install the epel repo key
  rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  register: rpm_status
  ignore_errors: yes

- name: epel debug
  debug:
    var: rpm_status

- name: record epel key status
  include_role:
    name: record_status
  vars:
    results: "{{ rpm_status }}"
    status_file: "/tmp/pbench_prep_status"

#
# Install the epel repo
#
- name: Install epel repo file
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: yum_status
  ignore_errors: yes

- name: record epel_rep_file status
  include_role:
    name: record_status
  vars:
    results: "{{ yum_status }}"
    status_file: "/tmp/pbench_prep_status"
