---
#
# tasks file for pbench_disk_setup
#
- name: include dynamic info
  include_vars:
    file: "{{ working_dir }}/ansible_run_vars.yml"
    name: dyn_data

#
# This is dumb
#
- name: Set fact because ansible is being brain dead.
  set_fact:
    ansible_ssh_private_key_file: "{{ config_info.ssh_key }}"
#
# Just keeping it simple for now.
# 
- name: make the pbench directory
  command: "ssh -oStrictHostKeyChecking=no {{ dyn_data.ssh_i_option }} {{ config_info.test_user }}@{{ target_sys }} sudo mkdir -p /var/lib/pbench-agent"

- name: Create the xfs file system
  command: "ssh -oStrictHostKeyChecking=no {{ dyn_data.ssh_i_option }} {{ config_info.test_user }}@{{ target_sys }} sudo mkfs.xfs -f -m uuid='7a617468-7261-7370-6265-6e6368000000'  {{ pbench_device }}"

#
# To get this to work right with AWS, we need to do things ugly
#
- name: Add pbench disk to fstab
  block:
    - name: get /etc/fstab
      command: "scp -oStrictHostKeyChecking=no {{ dyn_data.ssh_i_option }} {{ config_info.test_user }}@{{ target_sys }}:/etc/fstab {{ working_dir }}/fstab"
    - name: Now add to the end of that file
      lineinfile:
        path: "{{ working_dir }}/fstab"
        line: "UUID=7a617468-7261-7370-6265-6e6368000000  /var/lib/pbench-agent  xfs     defaults        0 0"
    - name: copy /etc/fstab back up
      command: "scp -oStrictHostKeyChecking=no {{ dyn_data.ssh_i_option }} {{ working_dir }}/fstab {{ config_info.test_user }}@{{ target_sys }}:/tmp/fstab"
    - name: Now move it
      command: "ssh -oStrictHostKeyChecking=no {{ dyn_data.ssh_i_option }} {{ config_info.test_user }}@{{ target_sys }} sudo mv -f /tmp/fstab /etc/fstab"

- name: mount the pbench direcotry
  command: "ssh -oStrictHostKeyChecking=no {{ dyn_data.ssh_i_option }} {{ config_info.test_user }}@{{ target_sys }} sudo mount {{ pbench_device }} /var/lib/pbench-agent"

